version: "3"

tasks:
  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/oms

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/oms

  deploy:
    cmds:
      - ssh sandbox-ovh -t "cd oms && docker compose pull && docker compose up -d --force-recreate web "
